'------------------------------------------------------------------------------
' <auto-generated>
'     This code was generated by a tool.
'     Runtime Version:4.0.30319.42000
'
'     Changes to this file may cause incorrect behavior and will be lost if
'     the code is regenerated.
' </auto-generated>
'------------------------------------------------------------------------------

Option Strict On
Option Explicit On

Imports System

Namespace My.Resources
    
    'This class was auto-generated by the StronglyTypedResourceBuilder
    'class via a tool like ResGen or Visual Studio.
    'To add or remove a member, edit your .ResX file then rerun ResGen
    'with the /str option, or rebuild your VS project.
    '''<summary>
    '''  A strongly-typed resource class, for looking up localized strings, etc.
    '''</summary>
    <Global.System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "16.0.0.0"),  _
     Global.System.Diagnostics.DebuggerNonUserCodeAttribute(),  _
     Global.System.Runtime.CompilerServices.CompilerGeneratedAttribute(),  _
     Global.Microsoft.VisualBasic.HideModuleNameAttribute()>  _
    Friend Module Resources
        
        Private resourceMan As Global.System.Resources.ResourceManager
        
        Private resourceCulture As Global.System.Globalization.CultureInfo
        
        '''<summary>
        '''  Returns the cached ResourceManager instance used by this class.
        '''</summary>
        <Global.System.ComponentModel.EditorBrowsableAttribute(Global.System.ComponentModel.EditorBrowsableState.Advanced)>  _
        Friend ReadOnly Property ResourceManager() As Global.System.Resources.ResourceManager
            Get
                If Object.ReferenceEquals(resourceMan, Nothing) Then
                    Dim temp As Global.System.Resources.ResourceManager = New Global.System.Resources.ResourceManager("SEL_FP_2022_01.Resources", GetType(Resources).Assembly)
                    resourceMan = temp
                End If
                Return resourceMan
            End Get
        End Property
        
        '''<summary>
        '''  Overrides the current thread's CurrentUICulture property for all
        '''  resource lookups using this strongly typed resource class.
        '''</summary>
        <Global.System.ComponentModel.EditorBrowsableAttribute(Global.System.ComponentModel.EditorBrowsableState.Advanced)>  _
        Friend Property Culture() As Global.System.Globalization.CultureInfo
            Get
                Return resourceCulture
            End Get
            Set
                resourceCulture = value
            End Set
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to SELECT	sys.objects.name		o_name,
        '''		sys.columns.name		c_name,
        '''			CASE
        '''									WHEN sys.columns.user_type_id IN (231, 239) THEN sys.columns.max_length / 2
        '''									ELSE sys.columns.max_length
        '''								END	c_len,
        '''		sys.types.name			t_name
        '''FROM	sys.objects
        '''		INNER JOIN sys.columns ON sys.objects.object_id = sys.columns.object_id
        '''		INNER JOIN sys.types	on sys.columns.user_type_id = sys.types.user_type_id
        '''WHERE	sys.columns.user_type_id IN (167, 175, 231, 239)
        '''		AND sys.objects.name = &apos;###TBNAME###&apos;
        '''		 [rest of string was truncated]&quot;;.
        '''</summary>
        Friend ReadOnly Property ColLenSelect() As String
            Get
                Return ResourceManager.GetString("ColLenSelect", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to Parameter &apos;TERMINAL&apos; wurde nicht eingegeben. Das Programm kann nicht gestartet werden..
        '''</summary>
        Friend ReadOnly Property DIALOG_1_D() As String
            Get
                Return ResourceManager.GetString("DIALOG_1_D", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to Parameter &apos;TERMINAL&apos; not specified. Program will be aborted..
        '''</summary>
        Friend ReadOnly Property DIALOG_1_GB() As String
            Get
                Return ResourceManager.GetString("DIALOG_1_GB", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to Nincs megadva a &apos;TERMINAL&apos; paraméter. A program így nem indítható el..
        '''</summary>
        Friend ReadOnly Property DIALOG_1_H() As String
            Get
                Return ResourceManager.GetString("DIALOG_1_H", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to FP_App.DoErrorMsgBox: Dialogbox konnte nicht erscheinen.
        '''</summary>
        Friend ReadOnly Property DIALOG_1000_D() As String
            Get
                Return ResourceManager.GetString("DIALOG_1000_D", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to FP_App.DoErrorMsgBox: Error by showing dialog..
        '''</summary>
        Friend ReadOnly Property DIALOG_1000_GB() As String
            Get
                Return ResourceManager.GetString("DIALOG_1000_GB", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to FP_App.DoErrorMsgBox: Hiba z üzenet megjelenítése közben..
        '''</summary>
        Friend ReadOnly Property DIALOG_1000_H() As String
            Get
                Return ResourceManager.GetString("DIALOG_1000_H", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to Parameters zur Database Connections fehlen..
        '''</summary>
        Friend ReadOnly Property DIALOG_1018_D() As String
            Get
                Return ResourceManager.GetString("DIALOG_1018_D", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to Database Connection Parameters are not given..
        '''</summary>
        Friend ReadOnly Property DIALOG_1018_GB() As String
            Get
                Return ResourceManager.GetString("DIALOG_1018_GB", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to Nincsenek megadva a kapcsolat paraméterei.
        '''</summary>
        Friend ReadOnly Property DIALOG_1018_H() As String
            Get
                Return ResourceManager.GetString("DIALOG_1018_H", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to Database konnte nicht erreichen..
        '''</summary>
        Friend ReadOnly Property DIALOG_1019_D() As String
            Get
                Return ResourceManager.GetString("DIALOG_1019_D", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to Wrong database connection..
        '''</summary>
        Friend ReadOnly Property DIALOG_1019_GB() As String
            Get
                Return ResourceManager.GetString("DIALOG_1019_GB", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to A megadott kapcsolatot nem tudtam megnyitni..
        '''</summary>
        Friend ReadOnly Property DIALOG_1019_H() As String
            Get
                Return ResourceManager.GetString("DIALOG_1019_H", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to Das angegebene Database ist kein SELEXPED Database.
        '''</summary>
        Friend ReadOnly Property DIALOG_1020_D() As String
            Get
                Return ResourceManager.GetString("DIALOG_1020_D", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to This is not a SELEXPED database..
        '''</summary>
        Friend ReadOnly Property DIALOG_1020_GB() As String
            Get
                Return ResourceManager.GetString("DIALOG_1020_GB", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to A megadott adatbázis nem Selexped adatbázis..
        '''</summary>
        Friend ReadOnly Property DIALOG_1020_H() As String
            Get
                Return ResourceManager.GetString("DIALOG_1020_H", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to Programms Versionsnumber (@0) ist ungleich mit Database Versionsnumber (@1).
        '''</summary>
        Friend ReadOnly Property DIALOG_1021_D() As String
            Get
                Return ResourceManager.GetString("DIALOG_1021_D", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to Program versionsnumber (@0) is not the same with the versionsnumber of the database (@1).
        '''</summary>
        Friend ReadOnly Property DIALOG_1021_GB() As String
            Get
                Return ResourceManager.GetString("DIALOG_1021_GB", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to A program verziószáma (@0) nem egyezik meg az adatbázis verziószámával (@1)..
        '''</summary>
        Friend ReadOnly Property DIALOG_1021_H() As String
            Get
                Return ResourceManager.GetString("DIALOG_1021_H", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to Connection Test wurde ERFOLGREICH beendet..
        '''</summary>
        Friend ReadOnly Property DIALOG_2_D() As String
            Get
                Return ResourceManager.GetString("DIALOG_2_D", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to Connection Test SUCCESFULL.
        '''</summary>
        Friend ReadOnly Property DIALOG_2_GB() As String
            Get
                Return ResourceManager.GetString("DIALOG_2_GB", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to A tesztek SIKERESEN befejeződtek..
        '''</summary>
        Friend ReadOnly Property DIALOG_2_H() As String
            Get
                Return ResourceManager.GetString("DIALOG_2_H", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to Az Ön képernyőjén a szövegek nagyítása be van kapcsolva. Ez torzíthatja és jelentősen lassíthatja a program megjelenítését..
        '''</summary>
        Friend ReadOnly Property DIALOG_3_D() As String
            Get
                Return ResourceManager.GetString("DIALOG_3_D", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to Az Ön képernyőjén a szövegek nagyítása be van kapcsolva. Ez torzíthatja és jelentősen lassíthatja a program megjelenítését..
        '''</summary>
        Friend ReadOnly Property DIALOG_3_GB() As String
            Get
                Return ResourceManager.GetString("DIALOG_3_GB", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to Az Ön képernyőjén a szövegek nagyítása be van kapcsolva. Ez torzíthatja és jelentősen lassíthatja a program megjelenítését..
        '''</summary>
        Friend ReadOnly Property DIALOG_3_H() As String
            Get
                Return ResourceManager.GetString("DIALOG_3_H", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to Internal Programmfehler. Code: @0. @1.
        '''</summary>
        Friend ReadOnly Property DIALOG_31_D() As String
            Get
                Return ResourceManager.GetString("DIALOG_31_D", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to Internal Error. Code: @0. @1.
        '''</summary>
        Friend ReadOnly Property DIALOG_31_GB() As String
            Get
                Return ResourceManager.GetString("DIALOG_31_GB", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to Futásidejű hiba. Hibakód: @0. @1.
        '''</summary>
        Friend ReadOnly Property DIALOG_31_H() As String
            Get
                Return ResourceManager.GetString("DIALOG_31_H", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to Database konnte nicht erreichen. Bitte überprüfen Sie den Netzwerk. Auf &quot;OK&quot; ich probiere es nochmals. .
        '''</summary>
        Friend ReadOnly Property DIALOG_4_D() As String
            Get
                Return ResourceManager.GetString("DIALOG_4_D", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to Database connection error. Try again..
        '''</summary>
        Friend ReadOnly Property DIALOG_4_GB() As String
            Get
                Return ResourceManager.GetString("DIALOG_4_GB", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to Nem sikerült kapcsolódni az adatbázishoz. Lehet, hogy nincs hálózati kapcsolat vagy internet kapcsolat. Kérem ellenőrizze. Az OK lenyomására ismét megpróbálok kapcsolódni..
        '''</summary>
        Friend ReadOnly Property DIALOG_4_H() As String
            Get
                Return ResourceManager.GetString("DIALOG_4_H", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to Eingabe zwingend.
        '''</summary>
        Friend ReadOnly Property DIALOG_7_D() As String
            Get
                Return ResourceManager.GetString("DIALOG_7_D", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to Field is mandatory.
        '''</summary>
        Friend ReadOnly Property DIALOG_7_GB() As String
            Get
                Return ResourceManager.GetString("DIALOG_7_GB", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to Adatmegadás kötelező.
        '''</summary>
        Friend ReadOnly Property DIALOG_7_H() As String
            Get
                Return ResourceManager.GetString("DIALOG_7_H", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to Parameter &quot;Terminal&quot; darf maximale Länge ist 10 Character..
        '''</summary>
        Friend ReadOnly Property DIALOG_8_D() As String
            Get
                Return ResourceManager.GetString("DIALOG_8_D", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to Max length of parameter &quot;Terminal&quot; is 10 character..
        '''</summary>
        Friend ReadOnly Property DIALOG_8_GB() As String
            Get
                Return ResourceManager.GetString("DIALOG_8_GB", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to A Terminál azonosító max. 10 karakterből állhat (és nem tartalmazhat szóközöket)..
        '''</summary>
        Friend ReadOnly Property DIALOG_8_H() As String
            Get
                Return ResourceManager.GetString("DIALOG_8_H", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to Dieser Terminalname ist schon besetzt. Bitte geben Sie einen anderen Name..
        '''</summary>
        Friend ReadOnly Property DIALOG_9_D() As String
            Get
                Return ResourceManager.GetString("DIALOG_9_D", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to This terminal name already exists. Please enter a new name..
        '''</summary>
        Friend ReadOnly Property DIALOG_9_GB() As String
            Get
                Return ResourceManager.GetString("DIALOG_9_GB", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to Ez a terminál már foglalt, kérem adjon meg egy másik értéket..
        '''</summary>
        Friend ReadOnly Property DIALOG_9_H() As String
            Get
                Return ResourceManager.GetString("DIALOG_9_H", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to SQL-Server:.
        '''</summary>
        Friend ReadOnly Property FP_DB_PLACE_1_D() As String
            Get
                Return ResourceManager.GetString("FP_DB_PLACE_1_D", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to SQL-Server:.
        '''</summary>
        Friend ReadOnly Property FP_DB_PLACE_1_GB() As String
            Get
                Return ResourceManager.GetString("FP_DB_PLACE_1_GB", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to SQL-szerver:.
        '''</summary>
        Friend ReadOnly Property FP_DB_PLACE_1_H() As String
            Get
                Return ResourceManager.GetString("FP_DB_PLACE_1_H", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to Computer Name:.
        '''</summary>
        Friend ReadOnly Property FP_DB_PLACE_10_D() As String
            Get
                Return ResourceManager.GetString("FP_DB_PLACE_10_D", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to Computer name:.
        '''</summary>
        Friend ReadOnly Property FP_DB_PLACE_10_GB() As String
            Get
                Return ResourceManager.GetString("FP_DB_PLACE_10_GB", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to Számítógép neve:.
        '''</summary>
        Friend ReadOnly Property FP_DB_PLACE_10_H() As String
            Get
                Return ResourceManager.GetString("FP_DB_PLACE_10_H", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to Programmverzeichniss:.
        '''</summary>
        Friend ReadOnly Property FP_DB_PLACE_11_D() As String
            Get
                Return ResourceManager.GetString("FP_DB_PLACE_11_D", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to Startup path:.
        '''</summary>
        Friend ReadOnly Property FP_DB_PLACE_11_GB() As String
            Get
                Return ResourceManager.GetString("FP_DB_PLACE_11_GB", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to Program könyvtár:.
        '''</summary>
        Friend ReadOnly Property FP_DB_PLACE_11_H() As String
            Get
                Return ResourceManager.GetString("FP_DB_PLACE_11_H", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to Microsoft SQL Server Connectivity Parameters:.
        '''</summary>
        Friend ReadOnly Property FP_DB_PLACE_12_D() As String
            Get
                Return ResourceManager.GetString("FP_DB_PLACE_12_D", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to Connect to Microsoft SQL Server.
        '''</summary>
        Friend ReadOnly Property FP_DB_PLACE_12_GB() As String
            Get
                Return ResourceManager.GetString("FP_DB_PLACE_12_GB", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to Microsoft SQL Server beállításai.
        '''</summary>
        Friend ReadOnly Property FP_DB_PLACE_12_H() As String
            Get
                Return ResourceManager.GetString("FP_DB_PLACE_12_H", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to SELEXPED Einstellungen.
        '''</summary>
        Friend ReadOnly Property FP_DB_PLACE_13_D() As String
            Get
                Return ResourceManager.GetString("FP_DB_PLACE_13_D", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to Connect to SELEXPED.
        '''</summary>
        Friend ReadOnly Property FP_DB_PLACE_13_GB() As String
            Get
                Return ResourceManager.GetString("FP_DB_PLACE_13_GB", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to SELEXPED beállításai.
        '''</summary>
        Friend ReadOnly Property FP_DB_PLACE_13_H() As String
            Get
                Return ResourceManager.GetString("FP_DB_PLACE_13_H", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to Verbindung zu Datenbank.
        '''</summary>
        Friend ReadOnly Property FP_DB_PLACE_14_D() As String
            Get
                Return ResourceManager.GetString("FP_DB_PLACE_14_D", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to Connect to database.
        '''</summary>
        Friend ReadOnly Property FP_DB_PLACE_14_GB() As String
            Get
                Return ResourceManager.GetString("FP_DB_PLACE_14_GB", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to Kapcsolódás az adatbázishoz.
        '''</summary>
        Friend ReadOnly Property FP_DB_PLACE_14_H() As String
            Get
                Return ResourceManager.GetString("FP_DB_PLACE_14_H", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to Database Name:.
        '''</summary>
        Friend ReadOnly Property FP_DB_PLACE_2_D() As String
            Get
                Return ResourceManager.GetString("FP_DB_PLACE_2_D", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to Database Name:.
        '''</summary>
        Friend ReadOnly Property FP_DB_PLACE_2_GB() As String
            Get
                Return ResourceManager.GetString("FP_DB_PLACE_2_GB", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to Adatbázis neve:.
        '''</summary>
        Friend ReadOnly Property FP_DB_PLACE_2_H() As String
            Get
                Return ResourceManager.GetString("FP_DB_PLACE_2_H", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to Windows NT Integrated Security.
        '''</summary>
        Friend ReadOnly Property FP_DB_PLACE_3_D() As String
            Get
                Return ResourceManager.GetString("FP_DB_PLACE_3_D", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to Use Windows NT Integrated security.
        '''</summary>
        Friend ReadOnly Property FP_DB_PLACE_3_GB() As String
            Get
                Return ResourceManager.GetString("FP_DB_PLACE_3_GB", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to Windows felhasználónév használata.
        '''</summary>
        Friend ReadOnly Property FP_DB_PLACE_3_H() As String
            Get
                Return ResourceManager.GetString("FP_DB_PLACE_3_H", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to User:.
        '''</summary>
        Friend ReadOnly Property FP_DB_PLACE_4_D() As String
            Get
                Return ResourceManager.GetString("FP_DB_PLACE_4_D", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to User:.
        '''</summary>
        Friend ReadOnly Property FP_DB_PLACE_4_GB() As String
            Get
                Return ResourceManager.GetString("FP_DB_PLACE_4_GB", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to Felhasználó:.
        '''</summary>
        Friend ReadOnly Property FP_DB_PLACE_4_H() As String
            Get
                Return ResourceManager.GetString("FP_DB_PLACE_4_H", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to Passwort:.
        '''</summary>
        Friend ReadOnly Property FP_DB_PLACE_5_D() As String
            Get
                Return ResourceManager.GetString("FP_DB_PLACE_5_D", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to Password:.
        '''</summary>
        Friend ReadOnly Property FP_DB_PLACE_5_GB() As String
            Get
                Return ResourceManager.GetString("FP_DB_PLACE_5_GB", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to Jelszó:.
        '''</summary>
        Friend ReadOnly Property FP_DB_PLACE_5_H() As String
            Get
                Return ResourceManager.GetString("FP_DB_PLACE_5_H", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to Test Connection.
        '''</summary>
        Friend ReadOnly Property FP_DB_PLACE_6_D() As String
            Get
                Return ResourceManager.GetString("FP_DB_PLACE_6_D", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to Test Connection.
        '''</summary>
        Friend ReadOnly Property FP_DB_PLACE_6_GB() As String
            Get
                Return ResourceManager.GetString("FP_DB_PLACE_6_GB", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to Kapcsolat tesztelése.
        '''</summary>
        Friend ReadOnly Property FP_DB_PLACE_6_H() As String
            Get
                Return ResourceManager.GetString("FP_DB_PLACE_6_H", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to OK.
        '''</summary>
        Friend ReadOnly Property FP_DB_PLACE_7_D() As String
            Get
                Return ResourceManager.GetString("FP_DB_PLACE_7_D", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to OK.
        '''</summary>
        Friend ReadOnly Property FP_DB_PLACE_7_GB() As String
            Get
                Return ResourceManager.GetString("FP_DB_PLACE_7_GB", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to OK.
        '''</summary>
        Friend ReadOnly Property FP_DB_PLACE_7_H() As String
            Get
                Return ResourceManager.GetString("FP_DB_PLACE_7_H", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to Hilfe zur Installation....
        '''</summary>
        Friend ReadOnly Property FP_DB_PLACE_8_D() As String
            Get
                Return ResourceManager.GetString("FP_DB_PLACE_8_D", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to Download Install Guide....
        '''</summary>
        Friend ReadOnly Property FP_DB_PLACE_8_GB() As String
            Get
                Return ResourceManager.GetString("FP_DB_PLACE_8_GB", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to Telepítő útmutató letöltése....
        '''</summary>
        Friend ReadOnly Property FP_DB_PLACE_8_H() As String
            Get
                Return ResourceManager.GetString("FP_DB_PLACE_8_H", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to Terminal:.
        '''</summary>
        Friend ReadOnly Property FP_DB_PLACE_9_D() As String
            Get
                Return ResourceManager.GetString("FP_DB_PLACE_9_D", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to Terminal:.
        '''</summary>
        Friend ReadOnly Property FP_DB_PLACE_9_GB() As String
            Get
                Return ResourceManager.GetString("FP_DB_PLACE_9_GB", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to Terminál:.
        '''</summary>
        Friend ReadOnly Property FP_DB_PLACE_9_H() As String
            Get
                Return ResourceManager.GetString("FP_DB_PLACE_9_H", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to Bitte geben Sie einen einheitlichen Identifierkennzeichen zu diesem Rechner (max 10 Buchstaben):.
        '''</summary>
        Friend ReadOnly Property INPUTBOX_1_D() As String
            Get
                Return ResourceManager.GetString("INPUTBOX_1_D", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to This terminal hasn&apos;t got unique ID yet. Please type an unique ID the box below (max. 10 character):.
        '''</summary>
        Friend ReadOnly Property INPUTBOX_1_GB() As String
            Get
                Return ResourceManager.GetString("INPUTBOX_1_GB", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to Kérem adjon meg ennek a számítógépnek egy max 10 jegyű egyedi azonosítót:.
        '''</summary>
        Friend ReadOnly Property INPUTBOX_1_H() As String
            Get
                Return ResourceManager.GetString("INPUTBOX_1_H", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to C:\Selester\HELP\D\SELEXPED_Hilfe_zur_Installation.doc.
        '''</summary>
        Friend ReadOnly Property LINK_INSTALL_GUIDE_1_D() As String
            Get
                Return ResourceManager.GetString("LINK_INSTALL_GUIDE_1_D", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to C:\Selester\HELP\GB\SELEXPED_Installations_Guide.doc.
        '''</summary>
        Friend ReadOnly Property LINK_INSTALL_GUIDE_1_GB() As String
            Get
                Return ResourceManager.GetString("LINK_INSTALL_GUIDE_1_GB", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to C:\Selester\HELP\H\SELEXPED_telepítö_segédlet.doc.
        '''</summary>
        Friend ReadOnly Property LINK_INSTALL_GUIDE_1_H() As String
            Get
                Return ResourceManager.GetString("LINK_INSTALL_GUIDE_1_H", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to CREATE TABLE LDB_Params(
        '''	Code nvarchar(20) NOT NULL	CONSTRAINT PK_LDB_Params PRIMARY KEY,
        '''	IntParam int NOT NULL,
        '''	StrParam ntext NOT NULL
        ''')
        '''
        '''#END_BAT#
        '''
        '''CREATE UNIQUE INDEX LDB_Params_Code ON LDB_Params (Code)
        '''
        '''#END_BAT#
        '''
        '''INSERT INTO LDB_Params	(Code, IntParam, StrParam)
        '''			VALUES		(&apos;LOCAL_DB_VERS&apos;, 0, &apos;&apos;)
        '''
        '''#END_BAT#
        '''
        '''CREATE TABLE RS_Fields(
        '''	FromTable int NOT NULL,
        '''	ServerObject_Prefix nvarchar(50) NOT NULL,
        '''	SubPrefix nvarchar(50) NOT NULL,
        '''	SeqNum int NOT NULL,
        '''	FieldName nvarchar( [rest of string was truncated]&quot;;.
        '''</summary>
        Friend ReadOnly Property LocalDB_SQL_CREATEDB_SEL() As String
            Get
                Return ResourceManager.GetString("LocalDB_SQL_CREATEDB_SEL", resourceCulture)
            End Get
        End Property
    End Module
End Namespace
